### ISSUE TITLE
Adblocker and firewall for apps installed on the device

### ISSUE THREAD

**Issue by newfern1990** [KaustubhPatange/Gear-VPN#14]
Feature request 

Adblocker and firewall for apps installed on the device.

**Comment by KaustubhPatange** [comment]
Hey @newfern1990,

I just want to know, what do you mean by this feature request? I don't understand, do you want me to add Adblock support in my VPN servers or something else. Kindly describe it precisely.

**Comment by newfern1990** [comment]
Yes adblocker and firewall
Adblocker to block ads (toggle to block ads or unblock ads)
Firewall (per app wise - block access of apps to mobile inernet or wifi)

Like you can only use the vpn

Then another option is vpn with adblock

Another option with all vpn adblock and fire wall

Check out rethinkdns app on playstore. (it will give you an idea of what I'm trying to relay here)

20-May-2022 21:27:19 Kaustubh Patange ***@***.***>:

**Comment by KaustubhPatange** [comment]
That is the DNS you are talking about, there is no need to add this separate feature. Here do this Go to Settings > Network & Internet > Private DNS & enter `dns.adguard.com`. That is it, there are lots of such DNS available for you to choose from, take a look at here https://kb.adguard.com/en/general/dns-providers
