### ISSUE TITLE
Importing .ovpn results in error "Invalid config file"

### ISSUE THREAD

**Issue by octoworld** [KaustubhPatange/Gear-VPN#16]
**Please complete the following information:**

- App Version [e.g. v1.0 (25)] - 1.0 (33) (from Playstore 3rd Sept
- Affected Device(s) Xiaomi Redmi 6, Android 9

**Describe the Bug:**

Importing .ovpn results error "Invalid config file"

Selecting CHANGE, IMPORT OPEN-VPN CONFIGURATION, Choose, browse to and select ovpn file.

**Expected Behavior:**

ovpn imports ok (it works on OpenVPN For Android)

ovpn file:

`client
dev tun
proto tcp
remote 194.35.233.214 443
resolv-retry infinite
remote-random
nobind
tun-mtu 1500
tun-mtu-extra 32
mssfix 1450
persist-key
persist-tun
ping 15
ping-restart 0
ping-timer-rem
reneg-sec 0
comp-lzo no
verify-x509-name CN=uk1807.nordvpn.com

remote-cert-tls server

auth-user-pass
verb 3
pull
fast-io
cipher AES-256-CBC
auth SHA512
<ca>
-----BEGIN CERTIFICATE-----
..
-----END CERTIFICATE-----
</ca>
key-direction 1
<tls-auth>
#
# 2048 bit OpenVPN static key
#
-----BEGIN OpenVPN Static key V1-----
..
-----END OpenVPN Static key V1-----
</tls-auth>`

**Comment by KaustubhPatange** [comment]
Yes, I'm aware of this issue. This will take time since I'm busy with other work but this will be fixed in an upcoming update along with other fixes.

**Comment by TonyStark** [comment]
not fixed yet?

**Comment by KaustubhPatange** [comment]
Really, I'll check and let you know!

**Comment by TonyStark** [comment]
yeah. im using version 1.0 (38)
even i tried to remove extra character from file name and put `.ovpn` or `.conf` config file in `/storage/emulated/0` and `root folder`
but still not working

**Comment by KaustubhPatange** [comment]
Can you attach the full file here, or if it is private can you mail me at developerkp16@gmail.com? This would help me to debug issue.

**Comment by TonyStark** [comment]
Sent....

**Comment by KaustubhPatange** [comment]
Can you try this build of Gear VPN https://github.com/KaustubhPatange/Gear-VPN/suites/10205710287/artifacts/499794228? Basically, it is a zip that contains the apk.

**Comment by KaustubhPatange** [comment]
Great, I've released a new version `1.0 (39)` on Google Play with this fix. Thanks for letting me know :)
