### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by mahdiboybird** [KaustubhPatange/Gear-VPN#19]
**Please complete the following information:**

- App Version [e.g. v1.0 (25)] - <specify>
- Affected Device(s) [e.g. Samsung Galaxy s10 with Android 9.0] (only for Android platform) - <specify>

**Describe the Bug:**

<Add a clear description about the problem.>

**Expected Behavior:**

<A clear description of what you expected to happen.>

**Comment by KaustubhPatange** [comment]
?
