### ISSUE TITLE
COMPILE ON AndroidIDE or AIDE FCS OR BOTH

### ISSUE THREAD

**Issue by cyberguard541** [KaustubhPatange/Gear-VPN#23]
I tried but I couldn't, could someone please modify the project to be compiled in AndroidIDE and Aide Fcs please, I would love to edit the application and modify mine way in my hours off work, or for example on my lunch break, if I could open the project in AndroidIDE and Anide FCS it would be wonderful, thanks

**Comment by KaustubhPatange** [comment]
Hi, sorry for the late reply. This is possible but would require you to additionally setup Kotlin as well as other gradle plugins manually. Unfortunately, I can't help you with this as it would be out of this project's scope. My 2 cents is just install Android Studio and get it up and running with no additional configuration.
